// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import

library; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:celest/celest.dart' as _i1;
import 'package:celest_backend/models.dart' as _i2;

abstract final class apis {
  static const greeting = _i1.CloudApi(name: r'greeting');

  static const todo = _i1.CloudApi(name: r'todo');
}

abstract final class functions {
  static const greetingSayHello = _i1.CloudFunction<String, String>(
    api: r'greeting',
    functionName: r'sayHello',
  );

  static const greetingSumTwoNumbers = _i1.CloudFunction<(int, int), int>(
    api: r'greeting',
    functionName: r'sumTwoNumbers',
  );

  static const todoCreateTodo =
      _i1.CloudFunction<({String title, bool completed}), _i2.Todo>(
    api: r'todo',
    functionName: r'createTodo',
  );

  static const todoDeleteTodo = _i1.CloudFunction<int, void>(
    api: r'todo',
    functionName: r'deleteTodo',
  );

  static const todoGetTodos = _i1.CloudFunction<void, List<_i2.Todo>>(
    api: r'todo',
    functionName: r'getTodos',
  );

  static const todoUpdateTodo =
      _i1.CloudFunction<({int id, String title, bool completed}), _i2.Todo>(
    api: r'todo',
    functionName: r'updateTodo',
  );
}
